extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - react-app
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier

plugins:
  - jsx-a11y
  - import
  - react-hooks
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'

rules:
  import/order: ["error", {"groups": ["builtin", ["external", "internal"], ["parent", "sibling", "index"]], "newlines-between": "always"}]
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx

  import/resolver:
    typescript:
      alwaysTryTypes: false
      directory: ./tsconfig.json
