env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  - '@typescript-eslint'

rules:
  import/order: [
    "error",
    {
      "groups": [
        "builtin",
        ["external", "internal"],
        ["parent", "sibling", "index"]
      ],
      "newlines-between": "always"
    }
  ]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always

settings:
  import/parsers:
    "@typescript-eslint/parser":
    - .ts
    - .tsx

  import/resolver:
    typescript:
      alwaysTryTypes: false
