FROM node:14.0.0-slim as frontend-build

ARG TARGET

WORKDIR /app/
COPY frontend/ /app/frontend/
COPY graphql/ /app/graphql/
COPY package.json yarn.lock /app/

RUN yarn install --frozen-lockfile
RUN yarn generate:frontend
RUN cd frontend && TARGET=${TARGET} yarn build

FROM nginx:alpine

WORKDIR /etc/nginx/
COPY --from=frontend-build /app/frontend/build/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
